### ISSUE TITLE
Updating content

### ISSUE THREAD

**Issue by kirstyrose** [kingsreach/kingsreach-online#21]
- Contact page needs updating with contact details
- "Two Slavard adventurers" needs correcting on Home Page
- Home page needs content fleshing out for "Immersive role play", "Monetary system" and "Weekly Events" sections.
- Typo needs correcting on Events page
- New screenshot images to be added to the Screenshots page

**Comment by adamkdean** [comment]
I think we need some way to group the screenshots into albums, or perhaps have feature screenshots.

#7 might be part of this.

**Comment by adamkdean** [comment]
Will do #7 another time along with new screenshots.
