### ISSUE TITLE
Donations dropdown sign thing

### ISSUE THREAD

**Issue by adamkdean** [kingsreach/kingsreach-online#39]
Our denizens have shown an interest in helping support the server. We should setup a donation page for this. PayPal? Patreon?

**Comment by adamkdean** [comment]
Link is here: https://www.patreon.com/kingsreach

**Comment by adamkdean** [comment]
I was thinking a ribbon or something in a corner.

**Comment by adamkdean** [comment]
Decided on a dropdown board. @kirstyrose could you pop this on?

**Comment by kirstyrose** [comment]
Done.
