### ISSUE TITLE
Map Template

### ISSUE THREAD

**Issue by kirstyrose** [kingsreach/kingsreach-online#40]
Separate template for pages such as the map.

**Comment by adamkdean** [comment]
Instead of doing this, I've added a variable `fixed` which the header/footer will react to.

If `fixed` is true, then `<header>` will remove it's `margin-bottom`, and `<footer>` will apply `display: none`.

**Comment by adamkdean** [comment]
Changes in this PR https://github.com/kingsreach/kingsreach-online/pull/41
