### ISSUE TITLE
Rule changes

### ISSUE THREAD

**Issue by adamkdean** [kingsreach/kingsreach-online#51]
URGENT ❗ 

Add naming rules (under RP):
- You must ensure that you choose an RP friendly name. If your name does not comply, then you may be asked to change it. A GM will assist you with this. 
- Your name must not be offensive, rude, or contain anything that is out of keeping with the server.

Add laddering rules (under Conduct):
- Building objects to scale walls (known as laddering) is not against the rules, but you must ensure these constructions are physically sound and realistic. Floating logs will not be tolerated, nor will climbing upon bark boxes.

Add a small area at top of rules page to state the moderation team.

Keepers of the Realm (GM)
- Ulfric Irongrip
- Kari Uvaersskyen

Wardens of the Realm (Moderators)
- Marta Dagfinn

**Comment by kirstyrose** [comment]
Done.
